In [1]:
import pandas as pd
df = pd.read_csv('clean_housing_data.csv') # load the new datset

df.head()

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR_BAY
1,1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR_BAY
2,2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR_BAY
3,3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR_BAY
4,4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR_BAY

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics


X = df[df.columns[0:-1]] # columns 0 to second last column contain non-class attributes 
y = df.ocean_proximity # store class lables in the variable y

# divide the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2) # note we using %80 training size

In [3]:
print('Depth, Criteria, Accuracy_score')

criteria = ["entropy", "gini"]

for crt in criteria:
    for depth in range(1,10):
        rfc = RandomForestClassifier(max_depth=depth, criterion=crt, n_estimators=10) # create an instance od DecisionTreeClassifier
        rfc.fit(X_train, y_train) # train teh classifier on the training data to learn a model 
        y_predicted = rfc.predict(X_test) # used the learned model to predict class labels for test values
        accuracy = metrics.accuracy_score(y_test,y_predicted) # compute the accuracy score by comparing actual and predicted class labels
        print(depth, '    ', crt , '    ', str(accuracy))

Depth, Criteria, Accuracy_score
1      entropy      0.5798874480058723
2      entropy      0.6978223635918767
3      entropy      0.7885979936383656
4      entropy      0.8211402006361634
5      entropy      0.8620014680694886
6      entropy      0.8876926841203817
7      entropy      0.903596770247125
8      entropy      0.9356496207487155
9      entropy      0.9542451676046
1      gini      0.5918766821629557
2      gini      0.7621727428431613
3      gini      0.7947149498409591
4      gini      0.8448739907022266
5      gini      0.8754587717151945
6      gini      0.8896501101052117
7      gini      0.9104477611940298
8      gini      0.9358942989968192
9      gini      0.9451920724247614