In [1]:
import pandas as pd

col_list = ['A' + str(i) for i in range(1, 17)] # assign headers(columns names) to the dataset

# import the data set from archive and assign the header 
df = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data", header=None, names=col_list) # import the data set

df.head() # quick look at the dataset including the header

  A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15 A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  00202    0   +
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g  00043  560   +
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  00280  824   +
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  00100    3   +
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  00120    0   +

In [2]:
# cleaning the data and prepar it 

for col_name in df.columns:   # loop over al the columns 
    col = df[col_name]
    miss = col.isnull().sum() # count how many values are missing 
    if miss > 0:              # if more than one value is missning 
        col.fillna(col.mode()[0], inplace = True) # replace missing values with the mode of that column

In [3]:
# other problem this dataset have is some of the values are '?' so we have to deal with it
# for example if we looka at first columns we should see only ('a' and 'b') values only 

set(df['A1']) # if we use set will return dictionary with 3 values

{'?', 'a', 'b'}

In [4]:
# with simple for loop we can see all the columns with '?' value 
for name_col in df[['A1', 'A4', 'A5', 'A7']]:
    name = df[name_col]
    print(set(df[name_col]))

{'b', 'a', '?'}
{'l', 'u', '?', 'y'}
{'gg', 'g', '?', 'p'}
{'h', 'bb', 'dd', 'z', 'ff', 'n', '?', 'o', 'j', 'v'}

In [5]:
# we can use replace method in pandas 
df = df.replace(['?'], method='bfill') # replace '?' values with next value

In [6]:
# check our work
for name_col in df[['A1', 'A4', 'A5', 'A7']]:
    name = df[name_col]
    print(set(df[name_col]))

{'b', 'a'}
{'l', 'u', 'y'}
{'gg', 'g', 'p'}
{'h', 'bb', 'dd', 'z', 'ff', 'n', 'o', 'j', 'v'}

In [7]:
df.to_csv('clean_crx.csv', index=False) # this is optional if you need to use clean data 
df = pd.read_csv('clean_crx.csv') 
df.head(20)

   A1     A2      A3 A4 A5  A6 A7     A8 A9 A10  A11 A12 A13  A14    A15 A16
0   b  30.83   0.000  u  g   w  v  1.250  t   t    1   f   g  202      0   +
1   a  58.67   4.460  u  g   q  h  3.040  t   t    6   f   g   43    560   +
2   a  24.50   0.500  u  g   q  h  1.500  t   f    0   f   g  280    824   +
3   b  27.83   1.540  u  g   w  v  3.750  t   t    5   t   g  100      3   +
4   b  20.17   5.625  u  g   w  v  1.710  t   f    0   f   s  120      0   +
5   b  32.08   4.000  u  g   m  v  2.500  t   f    0   t   g  360      0   +
6   b  33.17   1.040  u  g   r  h  6.500  t   f    0   t   g  164  31285   +
7   a  22.92  11.585  u  g  cc  v  0.040  t   f    0   f   g   80   1349   +
8   b  54.42   0.500  y  p   k  h  3.960  t   f    0   f   g  180    314   +
9   b  42.50   4.915  y  p   w  v  3.165  t   f    0   t   g   52   1442   +
10  b  22.08   0.830  u  g   c  h  2.165  f   f    0   t   g  128      0   +
11  b  29.92   1.835  u  g   c  h  4.335  t   f    0   f   g  260    200   +
12  a  38.25   6.000  u  g   k  v  1.000  t   f    0   t   g    0      0   +
13  b  48.08   6.040  u  g   k  v  0.040  f   f    0   f   g    0   2690   +
14  a  45.83  10.500  u  g   q  v  5.000  t   t    7   t   g    0      0   +
15  b  36.67   4.415  y  p   k  v  0.250  t   t   10   t   g  320      0   +
16  b  28.25   0.875  u  g   m  v  0.960  t   t    3   t   g  396      0   +
17  a  23.25   5.875  u  g   q  v  3.170  t   t   10   f   g  120    245   +
18  b  21.83   0.250  u  g   d  h  0.665  t   f    0   t   g    0      0   +
19  a  19.17   8.585  u  g  cc  h  0.750  t   t    7   f   g   96      0   +