# Get 4 hours data from Oanda

## This function will contact Oanda API for 4 hours time fram from 2010 until 2019

In [1]:
import pandas as pd
from oandapyV20 import API
import oandapyV20.endpoints.instruments as instruments
from time import sleep


def req_data(token, instruments_list):

    errors = 0
    errors_list = []
    
    for instrument in instruments_list:
    
        price_list = []
        
        months = [{'one':'01-01', 'two':'01-31'},
                 {'one':'02-01', 'two':'02-28'},
                 {'one':'03-01', 'two':'03-31'},
                 {'one':'04-01', 'two':'04-30'},
                 {'one':'05-01', 'two':'05-31'},
                 {'one':'06-01', 'two':'06-30'},
                 {'one':'07-01', 'two':'07-31'},
                 {'one':'08-01', 'two':'08-31'},
                 {'one':'09-01', 'two':'09-30'},
                 {'one':'10-01', 'two':'10-31'},
                 {'one':'11-01', 'two':'11-30'},
                 {'one':'12-01', 'two':'12-31'}]

        for price in range(2010,2019,1):
            
            for month in months:                        
                while True:
                    try:
                        time = []
                        _open = []
                        close = []
                        high = []
                        low = []
                        volume = []

                        if price == 2020:
                            _from = f"2018-12-31T00:00:00Z"
                            end = f"2019-06-30T00:00:00Z"
                            params= {"from":_from, "to":end, "granularity":"H4"}
                            client = API(access_token=token, environment='live')
                            r = instruments.InstrumentsCandles(instrument=instrument, params=params)
                            cli = client.request(r).get('candles')
                            for element in cli:
                                price_list.append(element)
                            print(instrument)
                            print(_from)
                            print(end)
                            print('Done')

                            _from = f"2019-06-30T00:00:00Z"
                            end = f"2019-12-19T00:00:00Z"
                            params= {"from":_from, "to":end, "granularity":"H4"}
                            client = API(access_token=token, environment='live')
                            r = instruments.InstrumentsCandles(instrument=instrument, params=params)
                            cli = client.request(r).get('candles')
                            for element_2 in cli:
                                price_list.append(element_2)
                            print(instrument)
                            print(_from)
                            print(end)
                            print('Done')

                        else:
                            _from = f"{price}-{month.get('one')}T00:00:00Z"
                            end = f"{price}-{month.get('two')}T23:00:00Z"
                            params= {"from":_from, "to":end, "granularity":"H4"}
                            client = API(access_token=token, environment='live')
                            r = instruments.InstrumentsCandles(instrument=instrument, params=params)
                            cli = client.request(r).get('candles')
                            for element in cli:
                                price_list.append(element)
                            print(instrument)
                            print(_from)
                            print(end)
                            print('Done')

                        for j in price_list:
                            time.append(j.get('time'))
                            _open.append(j.get('mid').get('o'))
                            close.append(j.get('mid').get('c'))
                            high.append(j.get('mid').get('h'))
                            low.append(j.get('mid').get('l'))
                            volume.append(j.get('volume'))
                    except:
                        errors +=1
                        print(list(zip([instrument],[_from],[end])))
                        errors_list.append(list(zip([instrument],[_from],[end])))
                        continue 


                    break 

        data_zip = list(zip(time, close, _open, high, low, volume))
        data = pd.DataFrame(data_zip, columns=[f'time_{instrument}', f'close_{instrument}', 
                                               f'open_{instrument}', f'high_{instrument}', 
                                               f'low_{instrument}',f'Volume_{instrument}'])
        
        data.to_csv(f'Dataset/{instrument}.csv', index=False)
    
    print(errors_list)
    print(f"Done! with {errors} errors")

In [2]:
token='ee266a3bb2bf2d6f3c9b080f1c3d19f5-4244665b19b9953b8117133df1bed0da'

inst_list = ['EUR_USD']

req_data(token=token, instruments_list=inst_list)

EUR_USD
2010-01-01T00:00:00Z
2010-01-31T23:00:00Z
Done
EUR_USD
2010-02-01T00:00:00Z
2010-02-28T23:00:00Z
Done
EUR_USD
2010-03-01T00:00:00Z
2010-03-31T23:00:00Z
Done
EUR_USD
2010-04-01T00:00:00Z
2010-04-30T23:00:00Z
Done
EUR_USD
2010-05-01T00:00:00Z
2010-05-31T23:00:00Z
Done
[('EUR_USD', '2010-06-01T00:00:00Z', '2010-06-30T23:00:00Z')]
EUR_USD
2010-06-01T00:00:00Z
2010-06-30T23:00:00Z
Done
EUR_USD
2010-07-01T00:00:00Z
2010-07-31T23:00:00Z
Done
EUR_USD
2010-08-01T00:00:00Z
2010-08-31T23:00:00Z
Done
EUR_USD
2010-09-01T00:00:00Z
2010-09-30T23:00:00Z
Done
EUR_USD
2010-10-01T00:00:00Z
2010-10-31T23:00:00Z
Done
EUR_USD
2010-11-01T00:00:00Z
2010-11-30T23:00:00Z
Done
EUR_USD
2010-12-01T00:00:00Z
2010-12-31T23:00:00Z
Done
EUR_USD
2011-01-01T00:00:00Z
2011-01-31T23:00:00Z
Done
EUR_USD
2011-02-01T00:00:00Z
2011-02-28T23:00:00Z
Done
EUR_USD
2011-03-01T00:00:00Z
2011-03-31T23:00:00Z
Done
EUR_USD
2011-04-01T00:00:00Z
2011-04-30T23:00:00Z
Done
EUR_USD
2011-05-01T00:00:00Z
2011-05-31T23:00:00Z
Done
EUR_USD
2011-06-01T00:00:00Z
2011-06-30T23:00:00Z
Done
EUR_USD
2011-07-01T00:00:00Z
2011-07-31T23:00:00Z
Done
EUR_USD
2011-08-01T00:00:00Z
2011-08-31T23:00:00Z
Done
EUR_USD
2011-09-01T00:00:00Z
2011-09-30T23:00:00Z
Done
EUR_USD
2011-10-01T00:00:00Z
2011-10-31T23:00:00Z
Done
EUR_USD
2011-11-01T00:00:00Z
2011-11-30T23:00:00Z
Done
EUR_USD
2011-12-01T00:00:00Z
2011-12-31T23:00:00Z
Done
EUR_USD
2012-01-01T00:00:00Z
2012-01-31T23:00:00Z
Done
EUR_USD
2012-02-01T00:00:00Z
2012-02-28T23:00:00Z
Done
EUR_USD
2012-03-01T00:00:00Z
2012-03-31T23:00:00Z
Done
EUR_USD
2012-04-01T00:00:00Z
2012-04-30T23:00:00Z
Done
EUR_USD
2012-05-01T00:00:00Z
2012-05-31T23:00:00Z
Done
EUR_USD
2012-06-01T00:00:00Z
2012-06-30T23:00:00Z
Done
EUR_USD
2012-07-01T00:00:00Z
2012-07-31T23:00:00Z
Done
EUR_USD
2012-08-01T00:00:00Z
2012-08-31T23:00:00Z
Done
EUR_USD
2012-09-01T00:00:00Z
2012-09-30T23:00:00Z
Done
EUR_USD
2012-10-01T00:00:00Z
2012-10-31T23:00:00Z
Done
EUR_USD
2012-11-01T00:00:00Z
2012-11-30T23:00:00Z
Done
EUR_USD
2012-12-01T00:00:00Z
2012-12-31T23:00:00Z
Done
EUR_USD
2013-01-01T00:00:00Z
2013-01-31T23:00:00Z
Done
EUR_USD
2013-02-01T00:00:00Z
2013-02-28T23:00:00Z
Done
EUR_USD
2013-03-01T00:00:00Z
2013-03-31T23:00:00Z
Done
EUR_USD
2013-04-01T00:00:00Z
2013-04-30T23:00:00Z
Done
EUR_USD
2013-05-01T00:00:00Z
2013-05-31T23:00:00Z
Done
EUR_USD
2013-06-01T00:00:00Z
2013-06-30T23:00:00Z
Done
EUR_USD
2013-07-01T00:00:00Z
2013-07-31T23:00:00Z
Done
EUR_USD
2013-08-01T00:00:00Z
2013-08-31T23:00:00Z
Done
EUR_USD
2013-09-01T00:00:00Z
2013-09-30T23:00:00Z
Done
EUR_USD
2013-10-01T00:00:00Z
2013-10-31T23:00:00Z
Done
EUR_USD
2013-11-01T00:00:00Z
2013-11-30T23:00:00Z
Done
EUR_USD
2013-12-01T00:00:00Z
2013-12-31T23:00:00Z
Done
EUR_USD
2014-01-01T00:00:00Z
2014-01-31T23:00:00Z
Done
EUR_USD
2014-02-01T00:00:00Z
2014-02-28T23:00:00Z
Done
EUR_USD
2014-03-01T00:00:00Z
2014-03-31T23:00:00Z
Done
EUR_USD
2014-04-01T00:00:00Z
2014-04-30T23:00:00Z
Done
EUR_USD
2014-05-01T00:00:00Z
2014-05-31T23:00:00Z
Done
EUR_USD
2014-06-01T00:00:00Z
2014-06-30T23:00:00Z
Done
EUR_USD
2014-07-01T00:00:00Z
2014-07-31T23:00:00Z
Done
EUR_USD
2014-08-01T00:00:00Z
2014-08-31T23:00:00Z
Done
EUR_USD
2014-09-01T00:00:00Z
2014-09-30T23:00:00Z
Done
EUR_USD
2014-10-01T00:00:00Z
2014-10-31T23:00:00Z
Done
EUR_USD
2014-11-01T00:00:00Z
2014-11-30T23:00:00Z
Done
EUR_USD
2014-12-01T00:00:00Z
2014-12-31T23:00:00Z
Done
EUR_USD
2015-01-01T00:00:00Z
2015-01-31T23:00:00Z
Done
EUR_USD
2015-02-01T00:00:00Z
2015-02-28T23:00:00Z
Done
EUR_USD
2015-03-01T00:00:00Z
2015-03-31T23:00:00Z
Done
EUR_USD
2015-04-01T00:00:00Z
2015-04-30T23:00:00Z
Done
EUR_USD
2015-05-01T00:00:00Z
2015-05-31T23:00:00Z
Done
EUR_USD
2015-06-01T00:00:00Z
2015-06-30T23:00:00Z
Done
EUR_USD
2015-07-01T00:00:00Z
2015-07-31T23:00:00Z
Done
EUR_USD
2015-08-01T00:00:00Z
2015-08-31T23:00:00Z
Done
EUR_USD
2015-09-01T00:00:00Z
2015-09-30T23:00:00Z
Done
EUR_USD
2015-10-01T00:00:00Z
2015-10-31T23:00:00Z
Done
EUR_USD
2015-11-01T00:00:00Z
2015-11-30T23:00:00Z
Done
EUR_USD
2015-12-01T00:00:00Z
2015-12-31T23:00:00Z
Done
EUR_USD
2016-01-01T00:00:00Z
2016-01-31T23:00:00Z
Done
EUR_USD
2016-02-01T00:00:00Z
2016-02-28T23:00:00Z
Done
EUR_USD
2016-03-01T00:00:00Z
2016-03-31T23:00:00Z
Done
EUR_USD
2016-04-01T00:00:00Z
2016-04-30T23:00:00Z
Done
EUR_USD
2016-05-01T00:00:00Z
2016-05-31T23:00:00Z
Done
EUR_USD
2016-06-01T00:00:00Z
2016-06-30T23:00:00Z
Done
EUR_USD
2016-07-01T00:00:00Z
2016-07-31T23:00:00Z
Done
EUR_USD
2016-08-01T00:00:00Z
2016-08-31T23:00:00Z
Done
EUR_USD
2016-09-01T00:00:00Z
2016-09-30T23:00:00Z
Done
EUR_USD
2016-10-01T00:00:00Z
2016-10-31T23:00:00Z
Done
EUR_USD
2016-11-01T00:00:00Z
2016-11-30T23:00:00Z
Done
EUR_USD
2016-12-01T00:00:00Z
2016-12-31T23:00:00Z
Done
EUR_USD
2017-01-01T00:00:00Z
2017-01-31T23:00:00Z
Done
EUR_USD
2017-02-01T00:00:00Z
2017-02-28T23:00:00Z
Done
EUR_USD
2017-03-01T00:00:00Z
2017-03-31T23:00:00Z
Done
EUR_USD
2017-04-01T00:00:00Z
2017-04-30T23:00:00Z
Done
EUR_USD
2017-05-01T00:00:00Z
2017-05-31T23:00:00Z
Done
EUR_USD
2017-06-01T00:00:00Z
2017-06-30T23:00:00Z
Done
EUR_USD
2017-07-01T00:00:00Z
2017-07-31T23:00:00Z
Done
EUR_USD
2017-08-01T00:00:00Z
2017-08-31T23:00:00Z
Done
EUR_USD
2017-09-01T00:00:00Z
2017-09-30T23:00:00Z
Done
EUR_USD
2017-10-01T00:00:00Z
2017-10-31T23:00:00Z
Done
EUR_USD
2017-11-01T00:00:00Z
2017-11-30T23:00:00Z
Done
EUR_USD
2017-12-01T00:00:00Z
2017-12-31T23:00:00Z
Done
EUR_USD
2018-01-01T00:00:00Z
2018-01-31T23:00:00Z
Done
EUR_USD
2018-02-01T00:00:00Z
2018-02-28T23:00:00Z
Done
EUR_USD
2018-03-01T00:00:00Z
2018-03-31T23:00:00Z
Done
EUR_USD
2018-04-01T00:00:00Z
2018-04-30T23:00:00Z
Done
EUR_USD
2018-05-01T00:00:00Z
2018-05-31T23:00:00Z
Done
EUR_USD
2018-06-01T00:00:00Z
2018-06-30T23:00:00Z
Done
EUR_USD
2018-07-01T00:00:00Z
2018-07-31T23:00:00Z
Done
EUR_USD
2018-08-01T00:00:00Z
2018-08-31T23:00:00Z
Done
EUR_USD
2018-09-01T00:00:00Z
2018-09-30T23:00:00Z
Done
EUR_USD
2018-10-01T00:00:00Z
2018-10-31T23:00:00Z
Done
EUR_USD
2018-11-01T00:00:00Z
2018-11-30T23:00:00Z
Done
EUR_USD
2018-12-01T00:00:00Z
2018-12-31T23:00:00Z
Done
[[('EUR_USD', '2010-06-01T00:00:00Z', '2010-06-30T23:00:00Z')]]
Done! with 1 errors

In [5]:
data = pd.read_csv('Dataset/EUR_USD.csv')
data.head()

,time_EUR_USD,close_EUR_USD,open_EUR_USD,high_EUR_USD,low_EUR_USD,Volume_EUR_USD
0,2009-12-31T22:00:00.000000000Z,1.43120,1.43120,1.43120,1.43120,1
1,2010-01-03T14:00:00.000000000Z,1.43172,1.43120,1.43172,1.43120,3
2,2010-01-03T18:00:00.000000000Z,1.43036,1.43172,1.43425,1.42926,1024
3,2010-01-03T22:00:00.000000000Z,1.42714,1.43030,1.43358,1.42576,5994
4,2010-01-04T02:00:00.000000000Z,1.43012,1.42712,1.43089,1.42708,2836

### If we check the Volume we can see there is a lot of incorect data entery a long with the rest of close, open, high, and low. So I am going to remove them.

In [6]:
inst_list = ['EUR_USD']

In [16]:
for i in inst_list:    
    index = data[data[f'high_{i}'] == data[f'low_{i}']]
    for j in index[f'Volume_{i}']:
        index = data[data[f'high_{i}'] == data[f'low_{i}']].index
        data = data.drop(index=index, axis=0)
    data.to_csv(f'dataset/{i}.csv', index=False)
    print(i, 'Done')

EUR_USD Done

## If we check now

In [17]:
data = pd.read_csv('Dataset/EUR_USD.csv')
data.head()

,time_EUR_USD,close_EUR_USD,open_EUR_USD,high_EUR_USD,low_EUR_USD,Volume_EUR_USD
0,2010-01-03T14:00:00.000000000Z,1.43172,1.43120,1.43172,1.43120,3
1,2010-01-03T18:00:00.000000000Z,1.43036,1.43172,1.43425,1.42926,1024
2,2010-01-03T22:00:00.000000000Z,1.42714,1.43030,1.43358,1.42576,5994
3,2010-01-04T02:00:00.000000000Z,1.43012,1.42712,1.43089,1.42708,2836
4,2010-01-04T06:00:00.000000000Z,1.43948,1.43010,1.43964,1.42694,9020